language: cpp
sudo: false

cache:
  apt: true

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - g++-4.9

compiler:
    - gcc
    - clang

before_script:
    - mkdir build
    - cd build
    - cmake ..

script:
    - make
    - make check
